#!/bin/sh

syntax_error()
{
	print_help
	exit 1
}

print_help()
{
	printf "USAGE:
	\t./vimsync OPTION
	OPTIONS:
	\t-h       : show this help message
	\t-l       : sync with local files (you need to have cloned the repo for this to work)"
}

local_sync()
{
	if $force; then
		cp -fr .bashrc .config .local "$HOME"
	else
		cp -ir .bashrc .config .local "$HOME"
	fi
}

local_mode=false
force=false

while getopts lfh option; do
	case $option in
		(l)
			local_mode=true;;
		(f)
			force=true;;
		(h | *)
			syntax_error;;
	esac
done

if $force && ! $local_mode; then
	syntax_error
fi

if $local_mode; then
	local_sync
fi

setxkbmap -layout us -variant dvp -option caps:swapescape

killall konsole && konsole &
kwinrc --replace &
