#!/bin/sh

bad_option()
{
	usage
	exit 1
}

usage()
{
	printf "USAGE:
	\t./vimsync OPTION
	OPTIONS:
	\t-h       : show this help message
	\t-l       : sync with local files (you need to have cloned the repo for this to work)
	\t-f 			 : force the copy"
}

local_sync()
{
	if $force; then
		cp -fr .bashrc .config .local "$HOME"
	else
		cp -ir .bashrc .config .local "$HOME"
	fi
}

local_mode=false
force=false

while getopts lfh option; do
	case $option in
		(l)
			local_mode=true;;
		(f)
			force=true;;
		(h | *)
			bad_option;;
	esac
done

if $force && ! $local_mode; then
	bad_option
fi

if $local_mode; then
	local_sync
	setxkbmap -layout us -variant dvp -option caps:swapescape
	killall konsole && konsole &
	kwinrc --replace &
else
	bad_option
fi
